name: Run Pytest

on:
  push:
    branches:
      - main  # Adjust to match the branches you want this to trigger on
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Adjust to your project's Python version

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry


      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files

      - name: Run Pytest
        run: pytest
